<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    <PackageReference Include="xunit" Version="2.9.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.8.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microsoft.Extensions.Logging.Abstractions">
      <HintPath>C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App\9.0.11\Microsoft.Extensions.Logging.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="TBM.Application">
      <HintPath>..\..\src\TBM.Application\bin\$(Configuration)\net9.0\TBM.Application.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="TBM.Core">
      <HintPath>..\..\src\TBM.Core\bin\$(Configuration)\net9.0\TBM.Core.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>

</Project>
